name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Varunkumar-code-art
          outputs: |
            output/github-snake.svg?palette=github-light
            output/github-snake-dark.svg?palette=github-dark

      - name: Push Snake to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add output/
          git commit -m "Update Snake contribution graph" || exit 0
          git push origin HEAD:output
